name: 'Swift Client Build'
description: 'Builds Swift client from proto files'

inputs:
  proto-path:
    description: 'Path to proto files'
    required: true
  repo-path:
    description: 'Path to output directory for generated Swift files'
    required: true
  artifact-name:
    description: 'Name of the artifact to upload'
    required: true
  artifact-name-with-proto:
    description: 'Name of the artifact to upload with proto files'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install protoc and Swift plugin
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler git curl unzip

        # Install protoc-gen-swift
        PB_REL="https://github.com/protocolbuffers/protobuf/releases"
        curl -LO $PB_REL/download/v25.1/protoc-25.1-linux-x86_64.zip
        unzip protoc-25.1-linux-x86_64.zip -d ./.local
        export PATH="$PATH:$HOME/test/.local/bin"

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.repo-path }}

    - name: Generate Swift files from proto
      shell: bash
      run: |
        mkdir -p ${{ inputs.repo-path }}
        protoc \
          -I ./ \
          --experimental_allow_proto3_optional \
          --swift_out=${{ inputs.repo-path }} \
          ${{ inputs.proto-path }}

    - name: Upload generated files
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name-with-proto }}
        path: ${{ inputs.repo-path }}
        include-hidden-files: true
