GRPC {{host}}/auth.AuthEndpoint/Refresh

{
	"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDdXN0b21DbGFpbXMiOnsidXNlcklEIjoiNDNiZTk5YTMtOWMyNi00Y2U3LWI5ZDEtOTQ5YTEyMjgxMjI2IiwiaXNBZG1pbiI6dHJ1ZX0sIlRva2VuVHlwZSI6ImFjY2VzcyIsImV4cCI6MTc1NTY1MzQ4MSwianRpIjoiY2NmOTk0MzktMDdiMi00ODg1LTk1MDQtZDY1ZjA1MzJmYzUwIiwiaWF0IjoxNzU1NjQ5ODgxLCJpc3MiOiJib25hdmlpLmNvbSJ9.UWCKO11tCo_-ucOv9LP0ZRbSyQLL11DtxHzkxjRzPnQ"
}
