GRPC {{host}}/auth.AuthEndpoint/SignIn

{
  "application": {
    "build": "1",
    "bundleID": "1",
    "version": "1"
  },
  "device": {
    "deviceName": "ide",
    "modelName": "ide",
    "nameOS": "Android",
    "versionOS": "ide"
  },
  "email": "{{ email }}",
  "password": "{{ password }}",
  "deviceID": "12345"
}

> {%
client.global.set("accessToken", response.body.token.accessToken);
%}
