GRPC {{host}}/transaction.TransactionEndpoint/CreateTransaction

{
  "accessToken": "{{accessToken}}",
  "id": "GwUJOcpPSE+4M4Z7on9Q/w==",
  "accountGroupID": "VG5+LajIT8aIvHu0j3kvOQ==",
  "accountFromID": "cnWLFCWeS/eMyUQaMsSzng==",
  "accountToID": "2xxxddG3RB6rwdnB7/oJ0A==",
  "datetimeCreate": "2024-06-10T12:00:00Z",
  "dateTransaction": "2024-06-10T12:00:00Z",
  "note": "test",
  "isExecuted": true,
  "amountFrom": 10,
  "amountTo": 20,
  "type": "Consumption",
  "accountingInCharts": true,
  "tagIDs": ["GwUJOcpPSE+4M4Z7on9Q/w=="]
}
