GRPC {{host}}/user.UserEndpoint/GetUsers

{
  "accessToken": "{{accessToken}}",
  "filters": {
    "createdAtFrom": null,
    "createdAtTo": null,
    "ids": null,
    "isAdmin": null,
    "isBlocked": null,
    "isTariffActive": false,
    "isWebInterfaceOpened": null,
    "lastSeenAtFrom": null,
    "lastSeenAtTo": null,
    "searchString": null
  },
  "pagination": {
    "page": 1,
    "size": 2
  },
  "sorts": []
}
