GRPC {{host}}/user.UserEndpoint/UpdateUser

{
  "accessToken": "{{accessToken}}",
  "id": "4bae6c84-3a3b-4ec9-8263-db90fd5d3675",
  "firstName": null,
  "createdAt": null,
  "description": null,
  "isAdmin": true,
  "isBlocked": null,
  "isWebInterfaceOpened": null,
  "lastName": null,
  "lastSeenAt": null,
  "referrerID": null
}
